services:
  ammarriage-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ammarriage-prod
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
